# Generated by Django 5.0.6 on 2024-06-02 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('mal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('aired', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('scored_by', models.IntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AnimeApp.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('mal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('role', models.CharField(max_length=100)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='AnimeApp.anime')),
            ],
        ),
    ]
